pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        //clone the git repository
        git branch: 'main', url: 'https://github.com/Abhishek-Sontakke/Jenkins-Zero-To-Hero.git'
      }
    }

     stage('Build') {
      agent {
        docker { image 'maven:3.8.1-openjdk-17' }
      }
      steps {
         //run maven build
        sh 'mvn clean package'
      }
    }
    
  stage('Check java version') {
    agent {
        docker { image 'openjdk-17' }
      }
      steps {
        //Avaliable Java Version
        sh 'java --version'
        //compile with java version
        sh 'mvn clean complie'
      }
    }
    
    stage('Run') {
      agent {
        docker { image 'openjdk:17' }
      }
      steps {
         //run the java application
        sh 'java -cp multi-stage-multi-agent/src Main'
      }
    }
  }
}
